import { Jerarquizacion } from '../../modelo/jerarquizacion/jerarquizacion-modelo';
export class jerarquizacion_Global_Modelo {

    codigoe:     String ;
    nombreg:     String ;
    descrielem:  String ;
    especle:     String ;
    especranga:  String ;
    especrangb:  String ;
    especrangc:  String ;
    especrangd:  String ;
    habitat:     String ;
    permanencia: String ;
    gloctip:     String ;
    comtax:      String ;
    glestim:     String ;
    glestimcom:  String ;
    gabund:      String ;
    gabundcom:   String ;
    gdist:       String ;
    gdistcom:    String ;
    //página 2   String ;
    gleprot:     String ;
    gleprotcom:  String ;
    gamenaz:     String ;
    gamenazcom:  String ;
    gfragil:     String ;
    gfragilcom:  String ;
    gotroconsi:  String ;
    rangog:      String ;
    fecharg:     Date ;
    granrazon:   String ;
    gnecprotec:  String ;
    gnecinvent:  String ;
    gnecestudi:  String ;
    gnecmanejo:  String ;
    resrg:       String ;
    edautor:     String ;
    edicion:     Date ;
    actualizar:  Date ;
    globlalId:   Number;
    jERARQUIZACIONjerarquizacionid :Jerarquizacion;
}